Repository ITU-BDSA23-GROUP10/Chirp, pull requests merged in 2023-12, with the labels that each got.

#199 Add followers to profile, download button and cheeps to the profile page
  src/Chirp.Core/IAuthorRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/AuthorRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/UserRepository.cs
  src/Chirp.Infrastructure/Models/User.cs
  src/Chirp.Web/Pages/UserProfile.cshtml
  src/Chirp.Web/Pages/UserProfile.cshtml.cs
Labels: enhancement

#214 Cheeps require text and creates error
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/ViewComponents/WriteCheepFormViewComponent.cs
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-grid.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-grid.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-grid.min.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-grid.min.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.min.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-grid.rtl.min.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-reboot.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-reboot.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-reboot.min.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-reboot.min.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.min.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-reboot.rtl.min.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-utilities.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-utilities.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-utilities.min.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-utilities.min.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.min.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap-utilities.rtl.min.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap.min.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap.min.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap.rtl.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap.rtl.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap.rtl.min.css
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/css/bootstrap.rtl.min.css.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.bundle.js
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.bundle.js.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.esm.js
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.esm.js.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.esm.min.js
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.esm.min.js.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.js
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.js.map
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.min.js
  src/Chirp.Web/wwwroot/bootstrap-5.3.2-dist/js/bootstrap.min.js.map
Labels: enhancement

#219 Change email button on profile page and fix some styling issues
  src/Chirp.Core/IUserRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/UserRepository.cs
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/UserProfile.cshtml
  src/Chirp.Web/Pages/UserProfile.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
Labels: enhancement

#220 Added dev container support and made some post create commands
  .devcontainer/Dockerfile
  .devcontainer/ThankYou.md
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/mssql/installSQLtools.sh
  .devcontainer/mssql/postCreateCommand.sh
  .devcontainer/mssql/setup.sql
  src/Chirp.Web/appsettings.json
Labels: enhancement

#224 Ensured usertimeline's page numbers fits.
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: enhancement

#223 Test change email button (Integration tests & playwright tests)
  src/Chirp.Web/Pages/UserProfile.cshtml.cs
  test/Chirp.Razor.Tests/IntegrationTests.cs
  test/PlaywrightTests/UITesting.cs
Labels: enhancement

#218 All warnings cleared
  src/Chirp.Core/IAuthorRepository.cs
  src/Chirp.Core/ICheepRepository.cs
  src/Chirp.Core/IUserRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/AuthorRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/UserRepository.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserProfile.cshtml
  src/Chirp.Web/Pages/UserProfile.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/ViewComponents/WriteCheepFormViewComponent.cs
  test/Chirp.Razor.Tests/ChirpRazorHttpClient_UnitTests.cs
  test/Chirp.Razor.Tests/ChirpUnitTest.cs
  test/Chirp.Razor.Tests/IntegrationTests.cs
  test/ChirpDatabase.Tests/ChirpDatabaseTest.cs
Labels: enhancement

#236 added youtube embeds in cheeps
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: enhancement

#235 Add more test to the test suite
  src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
  src/Chirp.Infrastructure/Migrations/20231128113908_AddFollowers.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231128113908_AddFollowers.cs
  test/ChirpDatabase.Tests/ChirpDatabaseTest.cs
Labels: enhancement

#238 Hashtags in cheeps
  src/Chirp.Core/ICheepRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
  src/Chirp.Web/Pages/Hashtag.cshtml
  src/Chirp.Web/Pages/Hashtag.cshtml.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
Labels: enhancement

#242 Adding like to cheeps
  src/Chirp.Core/CheepDTO.cs
  src/Chirp.Core/IReactionRepository.cs
  src/Chirp.Core/ReactionDTO.cs
  src/Chirp.Infrastructure/ChirpDBContext.cs
  src/Chirp.Infrastructure/ChirpRepository/AuthorRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/ReactionRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/UserRepository.cs
  src/Chirp.Infrastructure/Migrations/20231206120603_addedLikeFunction.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231206120603_addedLikeFunction.cs
  src/Chirp.Infrastructure/Migrations/ChirpDBContextModelSnapshot.cs
  src/Chirp.Infrastructure/Models/Cheep.cs
  src/Chirp.Infrastructure/Models/Reaction.cs
  src/Chirp.Infrastructure/Models/User.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserProfile.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Program.cs
  src/Chirp.Web/ViewComponents/WriteCheepFormViewComponent.cs
Labels: enhancement

#249 Styling upgrades to like and dislike buttons
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/wwwroot/css/style.css
Labels: enhancement

#266 fixed the email update displaying wrong information
  src/Chirp.Web/Pages/UserProfile.cshtml
  src/Chirp.Web/Pages/UserProfile.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
Labels: bug

#256 Dockerize project so it runs with docker compose and updated readme
  .devcontainer/devcontainer.json
  Chirp.sln
  Dockerfile
  README.md
  cert_scripts/create_cert.ps1
  cert_scripts/create_cert.sh
  docker-compose.yml
  src/Chirp.Web/Pages/UserProfile.cshtml
  src/Chirp.Web/appsettings.json
  test/PlaywrightTests/PlaywrightTests.csproj
  test/PlaywrightTests/UITesting.cs
Labels: enhancement

#267 Fix button redirect with ajax
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
  src/Chirp.Web/wwwroot/js/script.js
Labels: enhancement

#268 Create repo test and context tests for database
  GlobalUsings.cs
  src/Chirp.Infrastructure/ChirpDBContext.cs
  src/Chirp.Infrastructure/ChirpRepository/UserRepository.cs
  test/Chirp.Razor.Tests/ChirpUnitTest.cs
  test/Chirp.Razor.Tests/RazorAPITests.cs
  test/ChirpDatabase.Tests/ChirpDatabase.Tests.csproj
  test/ChirpDatabase.Tests/ChirpDatabaseContextTest.cs
  test/ChirpDatabase.Tests/ChirpDatabaseRepositoryTest.cs
  test/ChirpDatabase.Tests/ChirpDatabaseTest.cs
  test/ChirpDatabase.Tests/DatabaseFixture.cs
Labels: enhancement

#274 Warnings cleanup
  src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/ReactionRepository.cs
  src/Chirp.Infrastructure/Models/Reaction.cs
  test/ChirpDatabase.Tests/ChirpDatabaseRepositoryTest.cs
Labels: enhancement

#277 All chirp.web pages now inheriting properly and small comment fixes
  src/Chirp.Web/Pages/BasePageModel.cs
  src/Chirp.Web/Pages/BindableClasses.cs
  src/Chirp.Web/Pages/Hashtag.cshtml
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/UserProfile.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/PagesData.cs
  src/Chirp.Web/Program.cs
Labels: enhancement

#273 Change access modifiers
  src/Chirp.Core/IAuthorRepository.cs
  src/Chirp.Core/ICheepRepository.cs
  src/Chirp.Core/IReactionRepository.cs
  src/Chirp.Core/IUserRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/AuthorRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/CheepRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/ReactionRepository.cs
  src/Chirp.Infrastructure/ChirpRepository/UserRepository.cs
  test/Chirp.Razor.Tests/IntegrationTests.cs
Labels: enhancement

#280 End2endtest + all playwright tests working
  docs/report.md
  test/PlaywrightTests/EndtoEnd.cs
  test/PlaywrightTests/UITesting.cs
Labels: bug

#283 main seq dia, missing legend
  docs/report_diagrams/UML_sequence_diagrams/main_bdsagroup10chirprazor_UML_act.puml
Labels: enhancement

#284 Diagrams.sequence calls
  docs/report_diagrams/UML_sequence_diagrams/msg_data_flow_seq_diagrams/publictimeline_authorised_postcheep_UML_seq.puml
  docs/report_diagrams/UML_sequence_diagrams/msg_data_flow_seq_diagrams/publictimeline_unauthorised_UML_seq.puml
Labels: documentation

#285 Seq report.
  docs/report.md
Labels: documentation
